### PR TITLE
remove code from __init__.py

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by srobertson** [comment]
Out of curiosity what problem does this solve or is this a standard I'm unaware of?

**Comment by graingert** [comment]
@srobertson if you have code in __init__ you end up with overlapping namespaces.

Eg you can't have a module and a variable in __init__.py with the same name

**Comment by graingert** [comment]
It also causes all the modules that __init__.py depends on to be loaded if you import any other module

**Comment by graingert** [comment]
it's something to be avoided except for backwards compatibility and namespace flattening.

**Pull request merged**
