### PR TITLE
Fix remaining flake8 errors

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by srobertson** [comment]
Mind squashing?

**Comment by graingert** [comment]
Kept them separate for easy review. I'm happy to squash, or let you squash

**Comment by srobertson** [comment]
Ahh round here, the author squashes after review. Is there an easy way for me to do it? Or do I have to take over your branch?

**Comment by graingert** [comment]
You can just fetch my branch, squash and push to master. I'll be able to do this myself in about 9-10 hours

**Comment by graingert** [comment]
@srobertson squashed

**Comment by graingert** [comment]
@srobertson all of the build issues were just travis going wrong

**Comment by srobertson** [comment]
Thanks!

**Pull request merged**
